# Generated by Django 5.1.2 on 2024-11-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=20)),
                ('task_description', models.TextField()),
                ('is_complete', models.BooleanField(default=False)),
                ('task_assign_date', models.DateField()),
            ],
        ),
    ]
